version: "3.8"

services:
  devopslabs-api:
    container_name: API
    build: ./API
    ports:
      - 5000:5000
    depends_on:
      - postgresdb
    restart: always

  postgresdb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgresdb:/data/postgres
    ports:
      - 5432:5432
    restart: always

volumes:
  postgresdb: