apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
type: Opaque
data:
  # echo -n 'YOUR_SECRET_KEY' | base64
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZGVmYXVsdC1wb3N0Z3Jlc3FsOjU0MzIvZGV2b3Bz #service name
  DATABASE_USERNAME: dXNlcg==
  DATABASE_PASSWORD: cGFzc3dk