# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "password"
  username: "user"
  password: "passwd"
  database: "devops"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-pv-claim"

volumePermissions:
  enabled: true
